version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network

# Nginx configuration    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - app-network



networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
